---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: users-debian-unstable
    image: debian:unstable
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: debian-unstable
